### ISSUE TITLE
Feature 1: User can view upcoming events

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/ajax-project#1]
## ⚙️ Feature

User can view events by either searching by location or by name of event.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="380" alt="Screen Shot 2022-12-27 at 6 47 02 PM" src="https://user-images.githubusercontent.com/103142603/209749222-66a3c244-8392-46a0-958e-dab09db16751.png">
<img width="378" alt="Screen Shot 2022-12-27 at 6 47 24 PM" src="https://user-images.githubusercontent.com/103142603/209749258-a7a0f089-6f62-4084-a960-21fae1e6f500.png">
<img width="377" alt="Screen Shot 2022-12-27 at 6 47 48 PM" src="https://user-images.githubusercontent.com/103142603/209749294-04b776f4-24d6-4b1a-85bd-0483fd2f1336.png">
<img width="379" alt="Screen Shot 2022-12-27 at 6 48 05 PM" src="https://user-images.githubusercontent.com/103142603/209749320-2a2053d6-ec62-41c7-a271-1406fef3392a.png">

<img width="175" alt="Screen Shot 2022-12-27 at 6 50 06 PM" src="https://user-images.githubusercontent.com/103142603/209749517-1a1f47cc-93ca-41e0-bbc3-8d5e48d27758.png">
<img width="177" alt="Screen Shot 2022-12-27 at 6 50 24 PM" src="https://user-images.githubusercontent.com/103142603/209749563-488844da-4cb9-4409-8779-e28202135508.png">
<img width="179" alt="Screen Shot 2022-12-27 at 6 50 19 PM" src="https://user-images.githubusercontent.com/103142603/209749565-ae4c2d05-93f6-4c64-b96e-10c59ce97efd.png">

<img width="177" alt="Screen Shot 2022-12-27 at 6 50 29 PM" src="https://user-images.githubusercontent.com/103142603/209749544-b9c4af69-f12d-4e4d-82f1-e15350b94edc.png">

## ✅ Task List

- [x]  If "Browse Events" button is clicked on the first screen, next screen with "Browse Events" is displayed.
- [x] If users click "Search" after a location or name is input, user is shown a list of related events.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
