### ISSUE TITLE
Feature 2: User can save upcoming events

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature 2: User can save upcoming events.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user searches using the browse feature, the user can click on the green icon labeled "Save" and have it saved to a "Saved Events" object, storing it for later.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="680" alt="Screen Shot 2022-12-27 at 6 59 13 PM" src="https://user-images.githubusercontent.com/103142603/209750347-db6652b1-2d79-4339-843e-40d5761238af.png">
<img width="181" alt="Screen Shot 2022-12-27 at 6 59 29 PM" src="https://user-images.githubusercontent.com/103142603/209750372-b1b1f0cc-f8a3-456b-85e7-c9b7cca4526b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Users can click on the green icon in the browse menu.
- [x] Event the is the parent of the icon clicked will be stored in an array to be used for later.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
