### ISSUE TITLE
Feature 3: Users can view their saved events

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view their saved events.

> ##### A description of how the application will work from the perspective of the user.

When a user clicks the "Save" icon after selecting a browsing method, that specific event that was chosen is then saved and displayed on the "Saved Events" screen on another tab. When the user clicks "Saved Events" they are brought to that screen and can view all the events they have saved.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="682" alt="Screen Shot 2022-12-27 at 7 02 55 PM" src="https://user-images.githubusercontent.com/103142603/209750649-bbb5ed36-9c74-47f8-9020-54a66c7592b4.png">
<img width="179" alt="Screen Shot 2022-12-27 at 7 03 11 PM" src="https://user-images.githubusercontent.com/103142603/209750673-b66dc06e-0ad3-4b71-a70a-d986b9514e95.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can click the "Saved Events" button after saving an event then be brought to a new screen where they can view their saved events.
- [x] Every event the user saved can be viewed on the "Saved Events" screen.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by BenGrimmius** [comment]
![Kapture 2023-04-28 at 16 31 12](https://user-images.githubusercontent.com/103142603/235270692-e3aca3fe-479d-47db-a832-d532a9f3ba2d.gif)
