### ISSUE TITLE
Feature 4: Users can share events with friends.

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 Users can share events with friends.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the "Share" button on the "Saved Events" screen, a pop up will appear asking to what email they would like to send the link. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="680" alt="Screen Shot 2022-12-27 at 7 09 27 PM" src="https://user-images.githubusercontent.com/103142603/209751167-c4f75365-db10-495a-8e9a-1a13412fa17f.png">
<img width="176" alt="Screen Shot 2022-12-27 at 7 09 47 PM" src="https://user-images.githubusercontent.com/103142603/209751188-ef7352ee-d81a-4fe9-8b13-1a77c5958605.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] If the user clicks "Share", a pop up will be displayed requesting an email.
- [ ] Ensure the email is a valid email.
- [ ] After email is input and the "Send" button is clicked, the link from Ticketmaster will be sent to the email provided.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
