### ISSUE TITLE
Feature 5: Users can click a link to purchase tickets for events.

### ISSUE THREAD

**Issue by BenGrimmius** [BenGrimmius/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click a link to purchase tickets for events.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user clicks the "Find Tickets", they will be redirected to a new tab with access to purchase the ticket from an external site.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="781" alt="Screen Shot 2022-12-27 at 7 15 54 PM" src="https://user-images.githubusercontent.com/103142603/209751715-c970af08-3a43-42f7-b962-d0007991be62.png">
<img width="585" alt="Screen Shot 2022-12-27 at 7 16 14 PM" src="https://user-images.githubusercontent.com/103142603/209751737-69c25252-01d5-4443-8b86-bb5302dca22e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] A "Find Tickets" button will be added to every event on every screen of the app.
- [ ] Clicking the "Find Tickets" button will open a new tab to choosing tickets from an external site.
- [ ] Ensure the original tab does not close.
- [ ] Ensure that click targets are either `<a>` or `<button>` elements.
- [ ] Ensure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
